name: Test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  milestone:
    types: [closed]

jobs:
  test-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Clone repo to check
        run: |
          git clone https://github.com/cascode-labs/release-milestone-action.git
      - name: Check repo
        run: |
          ls -al
          echo "-----"
          pwd
          ls -al release-milestone-action
      - uses: ./release-milestone-action/action.yml
      - name: Check Artifacts
        run: |
          ls -al
          if [ ! -f Release_Note_Log.md ]; then
            echo "Release Log was not created."
          else
            echo "Action successfully created release log."
          fi
